services:
  - type: web
    name: ai-title-generator
    runtime: docker
    repo: https://github.com/kinjalparmar58/ai-title-generator
    branch: main
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
